name: "Release (photos independent)"

on:
    workflow_dispatch: # Allow manually running the action
    push:
        # Run when a tag matching the pattern "photos-v*"" is pushed
        # See: [Note: Testing release workflows that are triggered by tags]
        tags:
            - "photos-v*"

env:
    FLUTTER_VERSION: "3.32.8"

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: mobile/apps/photos

        steps:
            - name: Checkout code and submodules
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Free up disk space
              run: |
                  echo "Initial disk usage:"
                  df -h /
                  # Get available space in KB
                  INITIAL=$(df / | awk 'NR==2 {print $4}')
                  
                  echo -e "\n=== Removing .NET SDK (~20-25GB) ==="
                  BEFORE=$(df / | awk 'NR==2 {print $4}')
                  START=$(date +%s)
                  sudo rm -rf /usr/share/dotnet
                  END=$(date +%s)
                  AFTER=$(df / | awk 'NR==2 {print $4}')
                  FREED=$(( (AFTER - BEFORE) / 1048576 ))  # Convert KB to GB
                  echo "Time: $((END-START))s | Freed: ${FREED}GB"
                  
                  echo -e "\n=== Removing cached tools (~5-10GB) ==="
                  BEFORE=$(df / | awk 'NR==2 {print $4}')
                  START=$(date +%s)
                  sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                  END=$(date +%s)
                  AFTER=$(df / | awk 'NR==2 {print $4}')
                  FREED=$(( (AFTER - BEFORE) / 1048576 ))
                  echo "Time: $((END-START))s | Freed: ${FREED}GB"
                  
                  echo -e "\n=== Final Summary ==="
                  FINAL=$(df / | awk 'NR==2 {print $4}')
                  TOTAL_FREED=$(( (FINAL - INITIAL) / 1048576 ))
                  echo "Total space freed: ${TOTAL_FREED}GB"
                  echo "Final disk usage:"
                  df -h /

            - name: Setup JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            - name: Install Flutter ${{ env.FLUTTER_VERSION  }}
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version: ${{ env.FLUTTER_VERSION  }}
                  cache: true

            - name: Install Flutter Rust Bridge
              run: cargo install flutter_rust_bridge_codegen

            - name: Generate Rust bindings
              run: flutter_rust_bridge_codegen generate

            - name: Setup keys
              uses: timheuer/base64-to-file@v1
              with:
                  fileName: "keystore/ente_photos_key.jks"
                  encodedString: "MIIKtgIBAzCCCmAGCSqGSIb3DQEHAaCCClEEggpNMIIKSTCCBbAGCSqGSIb3DQEHAaCCBaEEggWdMIIFmTCCBZUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFLiJ9005gFVnH315dEBO5mRcdC0OAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQaJ2BAMqZ9IoF/kRVeSay2gSCBNC1DlcFalsHRL408wFYfF1N9Mng5iZcWO2netISkJ15WjNJY01GpHzARQ32ONaP1+WzWfN3LrgyHS770qMp1qId1x16DpUjdSFzcLm31vhzC2lUVghnmtPeEzudyegLzQwfr3boNwZkUFAbU35w8FIrW0GgsyAEGk60X3oZd89sp5UcCN6Qn4fv8+YhhFgg3gipDdPAbuxpq+E7uiqFnchM1KJG91EESWPafw/yTg2y+E0CH+5hGT4nnFxG9EkulffKRh4PeFahIdsGEFNOtpN62LE2SASLo7KHEnGghvfUU0OFo3+3vDrwSt6DgnFJPdx4TSH7cFl2pS/pJ6R9RalVkr16oCbrX7dXxk5K9jztUchJKutOaG6cL1g+5LkBvA4EU6CfjCgW3nOJ2B6MUklxzJ1MfIq4Q0IYyHbTxrBQjnSaThVt8fqpqcsOpwvgS/0wzHHbHCeC5c4X4nutyRaJHAtNr0KqOyia9opLmhq9LcHe0o5KLxLXmVm7+ZBeFRGgqro1xq9Q5TslhAfixYzW1wZRYYqliVX39LiqU24J6ts/FzjgYkATh45zUe9wrZHqHO6aVy8WLB9uEx5BTf053k7t5adqufc69ppUqQEZzjH61ObnrS+nekFRCW8B0foFnzEZ4Z4Zc2xKtg/BTfJ8RUIo5rDTf66rg0k18aUp8nklQHzXfElSKJm5+PM/DCC/xi9z03+fLtxKuPQ9mmUutsUlZ3rDqjs+MuLyV9OsjC1EJ3mSeRSzBCLwEFI9f9U5uq4ojazQyrDd0N+M3lAa5aIBLa+LrcTG+k37DcH95acs+NOYg/8v6K09nk3B+zgK84TD4TanAAHzcaLv9HeU1fKJARJB7FPU57edN+10imZ6UJdxc07j0t5BEirX/aa1cjLWee1K8DA2wv5+/SIja7KcTt2SVo4Ranq5Ru12w/uK/WFpHiW/QcD0O0+fm3Ao8vsK9f9Nx/37rlDdWtCEXXEEgojdlTj8xeIKNiawf26wEDBAUfAdS2QwWInN+l2vYaN2srJEHo9tdJBRqUMFEHM5EQ+kAyFuReyMeHuDsVvmimlFK7K6cE1Igy1F8ABbMDs/pIxBlAD0Ogp5BQteT+h32W0apxQvEk8uni8kmQs1xd9xTjEUDRzbLvnu1nHhQMZzDLZt+EBca2sNCFUo2O7DNui1l7h+gqp938EyELhNVFCReAQM8Afs5XZ9JoX6MK79JC4Aa5szFKmchRLozCxhG0VEkBitv5e7ljvGNW7ibUJ/sHtoN+dHwfbZmu15KXJeBOj/13NuFfQxCN3QJ1oFd1tcGywZKOWjYbmmxq0klcMVHc3xkbRHKdgI+ivrW4fAG2Pxc6xW+n1jMeGYw7hKEU1Bua1JIx8hR6jNjgAbDlHhoqeupENLD/m56vsJXEdonq1N5RTkMA4kmgoKDg6uISo3BaejrFqc4Y4RSd0grNjxHaAly5t7iDTmlNP6T8AtXb7vLOB2LFixfplrQTfU5cspqObf5fSUvNh72PyRLDEx3ETjug648lrHMEMh+YVYGiEAEYgu74IOHd2E8c9mMb8wqMzDwRldTpPCcdXm9+L0NNkHtk+7HDdQy9w6krDn0yikwT4sav4rEpHa/j7I+1yP70TsO74fpNClwDFCMB0GCSqGSIb3DQEJFDEQHg4AdQBwAGwAbwBhAGQAMzAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNzQyNDU1OTU1ODA5MIIEkQYJKoZIhvcNAQcGoIIEgjCCBH4CAQAwggR3BgkqhkiG9w0BBwEwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFJQD6KeTmgm+d3TqVPQxTAkoAJr/AgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ1q1UOdv/8Qs2KHGPa0cnMICCBADRt7gw0gL820/GDGyE+GKSw2+XP0iC1259xTF1OCshbRcsonZ30UJ3roNI7iIGtNHjWGyz1G0gk0uBP3hjIX4ZCJ1+3AWmC2bykj++G1+B584fq/ouEWhtoAUcNuZaWIgugWfBC1GuwmMt0qCs7456ZTvOod8dKVApOs4p7Ct30FVDl1Jkh3zOmGZXztHjm/m+PLWHzj2UHau/sj5cydYejVTHFK2XL4glI6CMA3esODTRNPJVYiImIgjX7bQsOsyKTPjMji4NQG4YqxcyEemvFcBkWo9wu8h9+L7+2xv/0nVnOuZuGa/NGkQI6AkumjStsrM70lxv48nqc49jTsXU8d3FwURAqNhLj5xG26tHLCsdtMmgcwmdGAA7Epj/a7p91LNyFjkAaxVap5XcgXKWr+9ysULLZiHFBetsfCW/Ev9LUN/0MxtBYADQAS9PuUEin5erPch52OC74HRegioIjyYFrg4cONbE/+ZLspHcmwX0mp8Vmf/kl6N0kjmoZOzy7XYIzSEw/b7TrzUYnKH93qcpIWeeVyH6o76boYQpB0CMBhFVHb0YjGtozattVvsWQV5uKpVQLgeFOdkTQeYzhAXJU9h+z7bTSHs03+XLgkXYfppIHc1IDizh7mfc0lZ6+WGzcW2qgXOAVfsRf/NbRETzOSKwlleGuJ6DWvbGHuG4rCkHVSUBjd7KttW7aDIFbq82Um1VcVZ+BJfszIecUXuh75akR+SW28MEucg4MUs1w706Nme619H3JvH3QEPg5blOjHZDbaBL/Do63QebltTSVdL4uacIJW85In3ZO2ut51ZKcCX3s2wzmFjQdvbH1/MhQjn9OUwNChiDHQ5bKGsp/9F+AkzJcMUDuI10WOhCaB3WbVUWi8gMerfxpY7F1sg65NOmtCqFeq6vnnyUVgZ8m5szfLdqCM6aC2wG/5zztC5F+1Be+BGniWiFD/ASh1oqWvoAkv4xQn9KmzEsSN2Smf3CoDikzcmJvYIHr38S5L7PhgasOsK2Jv4uyGDZrMwUChRtvbaIhxt45+MHFwyacNPaM3e4tJZ87gf5fS87vbwjJ1tQb3NVF/3cMfivleKyUVWywYrVf6wYXxCXJtr4lJ6UwJ6gU8riq2wHai8BX0jWfPNwD7ZS8I69CpxUC+0lnSk1WthJq3678DzED8YcGm0e+5pC5c0bT/PPjXMFJ7ksS+D90FWV3LHcgHHSbu7eb+qgUMIU197wSrkJZhKpDazFerhC/VVZ2aisfKyeQqgAF9sUZs/KiDSsjsfbWJMu6PIrJ0nxTodrG+SW2FqvrflOHW1QHoCfqX7SvCbnXIeSERSwXwb98thxLheuxQypA5V3/WOPpb2HIfkGME0wMTANBglghkgBZQMEAgEFAAQgFGO0i7Vp3lZk9vl4tXHEI/PfBFaMmzOwOgLsM9uyLy0EFIT68xJwYZSCLlILr02IgSSbywZuAgInEA=="

            - name: Build independent APK
              run: |
                flutter build apk --dart-define=cronetHttpNoPlay=true --release --flavor independent
                mv build/app/outputs/flutter-apk/app-independent-release.apk build/app/outputs/flutter-apk/ente-${{ github.ref_name }}.apk
              env:
                  SIGNING_KEY_PATH: "/home/runner/work/_temp/keystore/ente_photos_key.jks"
                  SIGNING_KEY_ALIAS: "upload3"
                  SIGNING_KEY_PASSWORD: "password"
                  SIGNING_STORE_PASSWORD: "password"

            - name: Checksum
              run: sha256sum build/app/outputs/flutter-apk/ente-${{ github.ref_name }}.apk > build/app/outputs/flutter-apk/sha256sum

            - name: Create a draft GitHub release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "mobile/apps/photos/build/app/outputs/flutter-apk/ente-${{ github.ref_name }}.apk,mobile/apps/photos/build/app/outputs/flutter-apk/sha256sum"
                  draft: true
